In [3]:
import pandas as pd

In [55]:
import os
import pandas as pd

DIR_PATH = "/Users/ipekoner/Desktop/f1-ml/f1-data"

def load_and_preview_csv(file_name, dir_path):
    file_path =os.path.join(dir_path, file_name)
    df = pd.read_csv(file_path)
    return df.head(), df.info(), df.describe()

filenames = [f for f in os.listdir(DIR_PATH) if f.endswith(".csv")]

data_overview = {}

for file in filenames:
    data_overview[file] = load_and_preview_csv(file, DIR_PATH)

print(data_overview.keys())

print(os.listdir(DIR_PATH))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   circuitId   77 non-null     int64
 1   circuitRef  77 non-null     object
 2   name        77 non-null     object
 3   location    77 non-null     object
 4   country     77 non-null     object
 5   lat         77 non-null     float64
 6   lng         77 non-null     float64
 7   alt         77 non-null     int64
 8   url         77 non-null     object
dtypes: float64(2), int64(2), object(5)
memory usage: 5.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   statusId  139 non-null    int64
 1   status    139 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575029 entries, 0 to 575028
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   raceId        575029 non-null  int64
 1   driverId      575029 non-null  int64
 2   lap           575029 non-null  int64
 3   position      575029 non-null  int64
 4   time          575029 non-null  object
 5   milliseconds  575029 non-null  int64
dtypes: int64(5), object(1)
memory usage: 26.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   resultId        300 non-null    int64
 1   raceId          300 non-null    int64
 2   driverId        300 non-null    int64
 3   constructorId   300 non-null    int64
 4   number          300 non-null    int64
 5   grid            300 non-null    int64
 6   position        300 non-null    object
 7   positionText    300 non-null    object
 8   positionOrder   300 non-null    int64
 9   points          300 non-null    int64
 10  laps            300 non-null    int64
 11  time            300 non-null    object
 12  milliseconds    300 non-null    object
 13  fastestLap      300 non-null    object
 14  fastestLapTime  300 non-null    object
 15  statusId        300 non-null    int64
dtypes: int64(10), object(6)
memory usage: 37.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 859 entries, 0 to 858
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     859 non-null    int64
 1   driverRef    859 non-null    object
 2   number       859 non-null    object
 3   code         859 non-null    object
 4   forename     859 non-null    object
 5   surname      859 non-null    object
 6   dob          859 non-null    object
 7   nationality  859 non-null    object
 8   url          859 non-null    object
dtypes: int64(1), object(8)
memory usage: 60.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1125 non-null   int64
 1   year         1125 non-null   int64
 2   round        1125 non-null   int64
 3   circuitId    1125 non-null   int64
 4   name         1125 non-null   object
 5   date         1125 non-null   object
 6   time         1125 non-null   object
 7   url          1125 non-null   object
 8   fp1_date     1125 non-null   object
 9   fp1_time     1125 non-null   object
 10  fp2_date     1125 non-null   object
 11  fp2_time     1125 non-null   object
 12  fp3_date     1125 non-null   object
 13  fp3_time     1125 non-null   object
 14  quali_date   1125 non-null   object
 15  quali_time   1125 non-null   object
 16  sprint_date  1125 non-null   object
 17  sprint_time  1125 non-null   object
dtypes: int64(4), object(14)
memory usage: 158.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructorId   212 non-null    int64
 1   constructorRef  212 non-null    object
 2   name            212 non-null    object
 3   nationality     212 non-null    object
 4   url             212 non-null    object
dtypes: int64(1), object(4)
memory usage: 8.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13261 entries, 0 to 13260
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   constructorStandingsId  13261 non-null  int64
 1   raceId                  13261 non-null  int64
 2   constructorId           13261 non-null  int64
 3   points                  13261 non-null  float64
 4   position                13261 non-null  int64
 5   positionText            13261 non-null  object
 6   wins                    13261 non-null  int64
dtypes: float64(1), int64(5), object(1)
memory usage: 725.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10234 entries, 0 to 10233
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qualifyId      10234 non-null  int64
 1   raceId         10234 non-null  int64
 2   driverId       10234 non-null  int64
 3   constructorId  10234 non-null  int64
 4   number         10234 non-null  int64
 5   position       10234 non-null  int64
 6   q1             10234 non-null  object
 7   q2             10221 non-null  object
 8   q3             10207 non-null  object
dtypes: int64(6), object(3)
memory usage: 719.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34574 entries, 0 to 34573
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driverStandingsId  34574 non-null  int64
 1   raceId             34574 non-null  int64
 2   driverId           34574 non-null  int64
 3   points             34574 non-null  float64
 4   position           34574 non-null  int64
 5   positionText       34574 non-null  object
 6   wins               34574 non-null  int64
dtypes: float64(1), int64(5), object(1)
memory usage: 1.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12495 entries, 0 to 12494
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   constructorResultsId  12495 non-null  int64
 1   raceId                12495 non-null  int64
 2   constructorId         12495 non-null  int64
 3   points                12495 non-null  float64
 4   status                12495 non-null  object
dtypes: float64(1), int64(3), object(1)
memory usage: 488.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10945 entries, 0 to 10944
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   raceId        10945 non-null  int64
 1   driverId      10945 non-null  int64
 2   stop          10945 non-null  int64
 3   lap           10945 non-null  int64
 4   time          10945 non-null  object
 5   duration      10945 non-null  object
 6   milliseconds  10945 non-null  int64
dtypes: int64(5), object(2)
memory usage: 598.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    75 non-null     int64
 1   url     75 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26499 entries, 0 to 26498
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26499 non-null  int64
 1   raceId           26499 non-null  int64
 2   driverId         26499 non-null  int64
 3   constructorId    26499 non-null  int64
 4   number           26499 non-null  object
 5   grid             26499 non-null  int64
 6   position         26499 non-null  object
 7   positionText     26499 non-null  object
 8   positionOrder    26499 non-null  int64
 9   points           26499 non-null  float64
 10  laps             26499 non-null  int64
 11  time             26499 non-null  object
 12  milliseconds     26499 non-null  object
 13  fastestLap       26499 non-null  object
 14  rank             26499 non-null  object
 15  fastestLapTime   26499 non-null  object
 16  fastestLapSpeed  26499 non-null  object
 17  statusId         26499 non-null  int64
dtypes: float64(1), int64(8), object(9)
memory usage: 3.6+ MB
dict_keys(['circuits.csv', 'status.csv', 'lap_times.csv', 'sprint_results.csv', 'drivers.csv', 'races.csv', 'constructors.csv', 'constructor_standings.csv', 'qualifying.csv', 'driver_standings.csv', 'constructor_results.csv', 'pit_stops.csv', 'seasons.csv', 'results.csv'])
['circuits.csv', '.DS_Store', 'status.csv', 'lap_times.csv', 'sprint_results.csv', 'drivers.csv', 'races.csv', 'constructors.csv', 'constructor_standings.csv', 'qualifying.csv', 'driver_standings.csv', 'constructor_results.csv', 'pit_stops.csv', 'seasons.csv', 'results.csv']

In [60]:
import pandas as pd

results = pd.read_csv(os.path.join(DIR_PATH, "results.csv"))
drivers = pd.read_csv(os.path.join(DIR_PATH, "drivers.csv"))

results_subset = results[["raceId","driverId","constructorId","grid","position"]]

merged = results_subset.merge(drivers, on="driverId", how="inner")

final_df = merged[["raceId","driverId","constructorId","grid","position", "forename", "surname"]]

final_df

       raceId  driverId  constructorId  grid position  forename     surname
0          18         1              1     1        1     Lewis    Hamilton
1          18         2              2     5        2      Nick    Heidfeld
2          18         3              3     7        3      Nico     Rosberg
3          18         4              4    11        4  Fernando      Alonso
4          18         5              1     3        5    Heikki  Kovalainen
...       ...       ...            ...   ...      ...       ...         ...
26494    1131       822             15    18       16  Valtteri      Bottas
26495    1131       855             15    20       17    Guanyu        Zhou
26496    1131         4            117    15       18  Fernando      Alonso
26497    1131       858              3    19       19     Logan    Sargeant
26498    1131       846              1     2       20     Lando      Norris

[26499 rows x 7 columns]

In [66]:
races = pd.read_csv(os.path.join(DIR_PATH, "races.csv"))

merged = results.merge(drivers, on="driverId", how="inner") #merging drivers to results with the key as driverId 

merged = merged.merge(races[["raceId","name", "date"]], on="raceId", how="inner") #taking the merged and merging races to it with the selected columns with the key as raceId

final_df = merged[["raceId","name", "driverId","constructorId","date", "grid","position", "forename", "surname"]]

final_df

,raceId,name,driverId,constructorId,date,grid,position,forename,surname
0,18,Australian Grand Prix,1,1,2008-03-16,1,1,Lewis,Hamilton
1,18,Australian Grand Prix,2,2,2008-03-16,5,2,Nick,Heidfeld
2,18,Australian Grand Prix,3,3,2008-03-16,7,3,Nico,Rosberg
3,18,Australian Grand Prix,4,4,2008-03-16,11,4,Fernando,Alonso
4,18,Australian Grand Prix,5,1,2008-03-16,3,5,Heikki,Kovalainen
...,...,...,...,...,...,...,...,...,...
26494,1131,Austrian Grand Prix,822,15,2024-06-30,18,16,Valtteri,Bottas
26495,1131,Austrian Grand Prix,855,15,2024-06-30,20,17,Guanyu,Zhou
26496,1131,Austrian Grand Prix,4,117,2024-06-30,15,18,Fernando,Alonso
26497,1131,Austrian Grand Prix,858,3,2024-06-30,19,19,Logan,Sargeant
26498,1131,Austrian Grand Prix,846,1,2024-06-30,2,20,Lando,Norris

In [67]:
merged["grid"] = pd.to_numeric(merged["grid"], errors = "coerce")
merged["position"] = pd.to_numeric(merged["position"], errors = "coerce")

merged["delta"] = merged["grid"] - merged["position"]

print(merged[["raceId","name", "driverId","constructorId","grid","position", "forename", "surname", "delta"]])

final_df["delta"] = merged["grid"] - merged["position"]

final_df

       raceId                   name  driverId  constructorId  grid  position  \
0          18  Australian Grand Prix         1              1     1       1.0
1          18  Australian Grand Prix         2              2     5       2.0
2          18  Australian Grand Prix         3              3     7       3.0
3          18  Australian Grand Prix         4              4    11       4.0
4          18  Australian Grand Prix         5              1     3       5.0
...       ...                    ...       ...            ...   ...       ...
26494    1131    Austrian Grand Prix       822             15    18      16.0
26495    1131    Austrian Grand Prix       855             15    20      17.0
26496    1131    Austrian Grand Prix         4            117    15      18.0
26497    1131    Austrian Grand Prix       858              3    19      19.0
26498    1131    Austrian Grand Prix       846              1     2      20.0

       forename     surname  delta
0         Lewis    Hamilton    0.0
1          Nick    Heidfeld    3.0
2          Nico     Rosberg    4.0
3      Fernando      Alonso    7.0
4        Heikki  Kovalainen   -2.0
...         ...         ...    ...
26494  Valtteri      Bottas    2.0
26495    Guanyu        Zhou    3.0
26496  Fernando      Alonso   -3.0
26497     Logan    Sargeant    0.0
26498     Lando      Norris  -18.0

[26499 rows x 9 columns]

/var/folders/bt/h9lb88v13wl7_n5fd8dvlntr0000gp/T/ipykernel_95095/3778366350.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["delta"] = merged["grid"] - merged["position"]

,raceId,name,driverId,constructorId,date,grid,position,forename,surname,delta
0,18,Australian Grand Prix,1,1,2008-03-16,1,1,Lewis,Hamilton,0.0
1,18,Australian Grand Prix,2,2,2008-03-16,5,2,Nick,Heidfeld,3.0
2,18,Australian Grand Prix,3,3,2008-03-16,7,3,Nico,Rosberg,4.0
3,18,Australian Grand Prix,4,4,2008-03-16,11,4,Fernando,Alonso,7.0
4,18,Australian Grand Prix,5,1,2008-03-16,3,5,Heikki,Kovalainen,-2.0
...,...,...,...,...,...,...,...,...,...,...
26494,1131,Austrian Grand Prix,822,15,2024-06-30,18,16,Valtteri,Bottas,2.0
26495,1131,Austrian Grand Prix,855,15,2024-06-30,20,17,Guanyu,Zhou,3.0
26496,1131,Austrian Grand Prix,4,117,2024-06-30,15,18,Fernando,Alonso,-3.0
26497,1131,Austrian Grand Prix,858,3,2024-06-30,19,19,Logan,Sargeant,0.0
26498,1131,Austrian Grand Prix,846,1,2024-06-30,2,20,Lando,Norris,-18.0

In [68]:
teams = pd.read_csv(os.path.join(DIR_PATH, "constructors.csv"))
team_points = pd.read_csv(os.path.join(DIR_PATH, "constructor_results.csv"))

team_points = team_points[["raceId", "constructorId", "points"]].rename(
    columns={"points": "constructor_points"}
)
teams = teams[["constructorId", "name"]].rename(columns={"name": "constructor_name"})



merged = merged.merge(team_points, on=["raceId", "constructorId"], how="left")
merged = merged.merge(teams, on="constructorId", how="left")


merged = merged[["raceId","date","name", "driverId","constructorId","grid","position", "forename", "surname", "delta", "constructor_name", "constructor_points"]]

merged

,raceId,date,name,driverId,constructorId,grid,position,forename,surname,delta,constructor_name,constructor_points
0,18,2008-03-16,Australian Grand Prix,1,1,1,1.0,Lewis,Hamilton,0.0,McLaren,14.0
1,18,2008-03-16,Australian Grand Prix,2,2,5,2.0,Nick,Heidfeld,3.0,BMW Sauber,8.0
2,18,2008-03-16,Australian Grand Prix,3,3,7,3.0,Nico,Rosberg,4.0,Williams,9.0
3,18,2008-03-16,Australian Grand Prix,4,4,11,4.0,Fernando,Alonso,7.0,Renault,5.0
4,18,2008-03-16,Australian Grand Prix,5,1,3,5.0,Heikki,Kovalainen,-2.0,McLaren,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...
26494,1131,2024-06-30,Austrian Grand Prix,822,15,18,16.0,Valtteri,Bottas,2.0,Sauber,0.0
26495,1131,2024-06-30,Austrian Grand Prix,855,15,20,17.0,Guanyu,Zhou,3.0,Sauber,0.0
26496,1131,2024-06-30,Austrian Grand Prix,4,117,15,18.0,Fernando,Alonso,-3.0,Aston Martin,0.0
26497,1131,2024-06-30,Austrian Grand Prix,858,3,19,19.0,Logan,Sargeant,0.0,Williams,0.0
26498,1131,2024-06-30,Austrian Grand Prix,846,1,2,20.0,Lando,Norris,-18.0,McLaren,31.0

In [74]:
merged["position"] = pd.to_numeric(merged["position"], errors = "coerce")
merged["avg_position"] =merged.groupby("driverId")["position"].transform("mean")
merged = merged[["raceId","date","name", "driverId","constructorId","grid","position", "forename", "surname", "delta", "constructor_name", "constructor_points", "avg_position"]]
merged

,raceId,date,name,driverId,constructorId,grid,position,forename,surname,delta,constructor_name,constructor_points,avg_position
0,18,2008-03-16,Australian Grand Prix,1,1,1,1.0,Lewis,Hamilton,0.0,McLaren,14.0,3.576433
1,18,2008-03-16,Australian Grand Prix,2,2,5,2.0,Nick,Heidfeld,3.0,BMW Sauber,8.0,8.355072
2,18,2008-03-16,Australian Grand Prix,3,3,7,3.0,Nico,Rosberg,4.0,Williams,9.0,6.355932
3,18,2008-03-16,Australian Grand Prix,4,4,11,4.0,Fernando,Alonso,7.0,Renault,5.0,6.344720
4,18,2008-03-16,Australian Grand Prix,5,1,3,5.0,Heikki,Kovalainen,-2.0,McLaren,14.0,11.835165
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26494,1131,2024-06-30,Austrian Grand Prix,822,15,18,16.0,Valtteri,Bottas,2.0,Sauber,0.0,7.389423
26495,1131,2024-06-30,Austrian Grand Prix,855,15,20,17.0,Guanyu,Zhou,3.0,Sauber,0.0,13.521739
26496,1131,2024-06-30,Austrian Grand Prix,4,117,15,18.0,Fernando,Alonso,-3.0,Aston Martin,0.0,6.344720
26497,1131,2024-06-30,Austrian Grand Prix,858,3,19,19.0,Logan,Sargeant,0.0,Williams,0.0,15.760000
26498,1131,2024-06-30,Austrian Grand Prix,846,1,2,20.0,Lando,Norris,-18.0,McLaren,31.0,7.462264

In [83]:
total_avg_position = merged.groupby(["driverId", "surname"])["position"].mean().reset_index()

total_avg_position = total_avg_position.rename(columns={"position": "avg_position_total"})

total_avg_position.head()

   driverId     surname  avg_position_total
0         1    Hamilton            3.576433
1         2    Heidfeld            8.355072
2         3     Rosberg            6.355932
3         4      Alonso            6.344720
4         5  Kovalainen           11.835165